### ISSUE TITLE
Report page prompts alert window

### ISSUE THREAD

**Issue by uhaciogullari** [maciejmaciejewski/azure-pipelines-postman#15]
I get an alert every time I navigate to report page.

![postman report](https://user-images.githubusercontent.com/1431130/104737419-807cfe80-5744-11eb-9561-56acf0d9fc50.jpg)

Is this an XSS attack? Could you have have a look at this please?

**Comment by uhaciogullari** [comment]
I don't see it anymore. No idea what caused it or fixed it.

**Comment by maciejmaciejewski** [comment]
This might have been caused by postman plugin that generates the report or azure devops.
